// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface AllocationDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.AllocationDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 路径
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   * 路径
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>optional int32 status = 2;</code>
   */
  int getStatus();

  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 返回的 datanodes
   * </pre>
   *
   * <code>repeated .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto data_node_infos = 4;</code>
   */
  java.util.List<com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto> 
      getDataNodeInfosList();
  /**
   * <pre>
   * 返回的 datanodes
   * </pre>
   *
   * <code>repeated .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto data_node_infos = 4;</code>
   */
  com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto getDataNodeInfos(int index);
  /**
   * <pre>
   * 返回的 datanodes
   * </pre>
   *
   * <code>repeated .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto data_node_infos = 4;</code>
   */
  int getDataNodeInfosCount();
  /**
   * <pre>
   * 返回的 datanodes
   * </pre>
   *
   * <code>repeated .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto data_node_infos = 4;</code>
   */
  java.util.List<? extends com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder> 
      getDataNodeInfosOrBuilderList();
  /**
   * <pre>
   * 返回的 datanodes
   * </pre>
   *
   * <code>repeated .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto data_node_infos = 4;</code>
   */
  com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder getDataNodeInfosOrBuilder(
      int index);
}
