// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class ClientNameNodeProtol {
  private ClientNameNodeProtol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_RenameDirResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ClientNameNodeProtol.proto\022\036com.icloud" +
      "ing.mfs.rpc.namenode\"2\n\014MkDirRequest\022\014\n\004" +
      "path\030\001 \001(\t\022\024\n\014createParent\030\002 \001(\010\">\n\rMkDi" +
      "rResponse\022\014\n\004path\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022" +
      "\017\n\007message\030\003 \001(\t\"L\n\021CreateFileRequest\022\014\n" +
      "\004path\030\001 \001(\t\022\024\n\014createParent\030\002 \001(\010\022\023\n\013rep" +
      "lication\030\003 \001(\r\"C\n\022CreateFileResponse\022\014\n\004" +
      "path\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\017\n\007message\030\003 " +
      "\001(\t\"3\n\020RenameDirRequest\022\016\n\006srcDir\030\001 \001(\t\022" +
      "\017\n\007destDir\030\002 \001(\t\"B\n\021RenameDirResponse\022\014\n",
      "\004path\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\017\n\007message\030\003" +
      " \001(\tB>\n$com.iclouding.mfs.rpc.namenode.m" +
      "odelB\024ClientNameNodeProtolP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor,
        new java.lang.String[] { "Path", "CreateParent", });
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_CreateFileRequest_descriptor,
        new java.lang.String[] { "Path", "CreateParent", "Replication", });
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iclouding_mfs_rpc_namenode_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_CreateFileResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor,
        new java.lang.String[] { "SrcDir", "DestDir", });
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_iclouding_mfs_rpc_namenode_RenameDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_RenameDirResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
