// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class ClientNameNodeProtol {
  private ClientNameNodeProtol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_UploadFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_UploadFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ClientNameNodeProtol.proto\022\036com.icloud" +
      "ing.mfs.rpc.namenode\"2\n\014MkDirRequest\022\014\n\004" +
      "path\030\001 \001(\t\022\024\n\014createParent\030\002 \001(\010\">\n\rMkDi" +
      "rResponse\022\014\n\004path\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022" +
      "\017\n\007message\030\003 \001(\t\"3\n\rCreateRequest\022\014\n\004pat" +
      "h\030\001 \001(\t\022\024\n\014createParent\030\002 \001(\010\"?\n\016CreateR" +
      "esponse\022\014\n\004path\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\017\n" +
      "\007message\030\003 \001(\t\"?\n\021UploadFileRequest\022\014\n\004p" +
      "ath\030\001 \001(\t\022\013\n\003md5\030\002 \001(\t\022\017\n\007content\030\003 \001(\014\"" +
      "C\n\022UploadFileResponse\022\014\n\004path\030\001 \001(\t\022\016\n\006s",
      "tatus\030\002 \001(\005\022\017\n\007message\030\003 \001(\tB>\n$com.iclo" +
      "uding.mfs.rpc.namenode.modelB\024ClientName" +
      "NodeProtolP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_MkDirRequest_descriptor,
        new java.lang.String[] { "Path", "CreateParent", });
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_MkDirResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
    internal_static_com_iclouding_mfs_rpc_namenode_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iclouding_mfs_rpc_namenode_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_CreateRequest_descriptor,
        new java.lang.String[] { "Path", "CreateParent", });
    internal_static_com_iclouding_mfs_rpc_namenode_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iclouding_mfs_rpc_namenode_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_CreateResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_UploadFileRequest_descriptor,
        new java.lang.String[] { "Path", "Md5", "Content", });
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_iclouding_mfs_rpc_namenode_UploadFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_UploadFileResponse_descriptor,
        new java.lang.String[] { "Path", "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
