// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mfs.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface DataNodeInfoProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.DataNodeInfoProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string hostname = 2;</code>
   */
  java.lang.String getHostname();
  /**
   * <code>optional string hostname = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional int32 dataPort = 3;</code>
   */
  int getDataPort();

  /**
   * <code>optional int64 totalDiskSize = 4;</code>
   */
  long getTotalDiskSize();

  /**
   * <code>optional int64 usedDiskSize = 5;</code>
   */
  long getUsedDiskSize();
}
