// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StandByNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

/**
 * Protobuf type {@code com.iclouding.mfs.rpc.namenode.FetchEditLogResponse}
 */
public  final class FetchEditLogResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iclouding.mfs.rpc.namenode.FetchEditLogResponse)
    FetchEditLogResponseOrBuilder {
  // Use FetchEditLogResponse.newBuilder() to construct.
  private FetchEditLogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchEditLogResponse() {
    status_ = 0;
    beginTxid_ = 0L;
    editLogs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    fetchSize_ = 0;
    hasMore_ = false;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchEditLogResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            status_ = input.readInt32();
            break;
          }
          case 16: {

            beginTxid_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              editLogs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            editLogs_.add(s);
            break;
          }
          case 32: {

            fetchSize_ = input.readInt32();
            break;
          }
          case 40: {

            hasMore_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        editLogs_ = editLogs_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.class, com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>optional int32 status = 1;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int BEGINTXID_FIELD_NUMBER = 2;
  private long beginTxid_;
  /**
   * <code>optional int64 beginTxid = 2;</code>
   */
  public long getBeginTxid() {
    return beginTxid_;
  }

  public static final int EDITLOGS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList editLogs_;
  /**
   * <pre>
   * 存放editlogs的
   * </pre>
   *
   * <code>repeated string editLogs = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEditLogsList() {
    return editLogs_;
  }
  /**
   * <pre>
   * 存放editlogs的
   * </pre>
   *
   * <code>repeated string editLogs = 3;</code>
   */
  public int getEditLogsCount() {
    return editLogs_.size();
  }
  /**
   * <pre>
   * 存放editlogs的
   * </pre>
   *
   * <code>repeated string editLogs = 3;</code>
   */
  public java.lang.String getEditLogs(int index) {
    return editLogs_.get(index);
  }
  /**
   * <pre>
   * 存放editlogs的
   * </pre>
   *
   * <code>repeated string editLogs = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEditLogsBytes(int index) {
    return editLogs_.getByteString(index);
  }

  public static final int FETCHSIZE_FIELD_NUMBER = 4;
  private int fetchSize_;
  /**
   * <pre>
   * 获取editlog的数量
   * </pre>
   *
   * <code>optional int32 fetchSize = 4;</code>
   */
  public int getFetchSize() {
    return fetchSize_;
  }

  public static final int HASMORE_FIELD_NUMBER = 5;
  private boolean hasMore_;
  /**
   * <pre>
   * 是否还有后续editlog
   * </pre>
   *
   * <code>optional bool hasMore = 5;</code>
   */
  public boolean getHasMore() {
    return hasMore_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 6;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    if (beginTxid_ != 0L) {
      output.writeInt64(2, beginTxid_);
    }
    for (int i = 0; i < editLogs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, editLogs_.getRaw(i));
    }
    if (fetchSize_ != 0) {
      output.writeInt32(4, fetchSize_);
    }
    if (hasMore_ != false) {
      output.writeBool(5, hasMore_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    if (beginTxid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, beginTxid_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < editLogs_.size(); i++) {
        dataSize += computeStringSizeNoTag(editLogs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEditLogsList().size();
    }
    if (fetchSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, fetchSize_);
    }
    if (hasMore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, hasMore_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse)) {
      return super.equals(obj);
    }
    com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse other = (com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse) obj;

    boolean result = true;
    result = result && (getStatus()
        == other.getStatus());
    result = result && (getBeginTxid()
        == other.getBeginTxid());
    result = result && getEditLogsList()
        .equals(other.getEditLogsList());
    result = result && (getFetchSize()
        == other.getFetchSize());
    result = result && (getHasMore()
        == other.getHasMore());
    result = result && getMessage()
        .equals(other.getMessage());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + BEGINTXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBeginTxid());
    if (getEditLogsCount() > 0) {
      hash = (37 * hash) + EDITLOGS_FIELD_NUMBER;
      hash = (53 * hash) + getEditLogsList().hashCode();
    }
    hash = (37 * hash) + FETCHSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFetchSize();
    hash = (37 * hash) + HASMORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasMore());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iclouding.mfs.rpc.namenode.FetchEditLogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iclouding.mfs.rpc.namenode.FetchEditLogResponse)
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.class, com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.Builder.class);
    }

    // Construct using com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      beginTxid_ = 0L;

      editLogs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      fetchSize_ = 0;

      hasMore_ = false;

      message_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor;
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse getDefaultInstanceForType() {
      return com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.getDefaultInstance();
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse build() {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse buildPartial() {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse result = new com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.status_ = status_;
      result.beginTxid_ = beginTxid_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        editLogs_ = editLogs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.editLogs_ = editLogs_;
      result.fetchSize_ = fetchSize_;
      result.hasMore_ = hasMore_;
      result.message_ = message_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse) {
        return mergeFrom((com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse other) {
      if (other == com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getBeginTxid() != 0L) {
        setBeginTxid(other.getBeginTxid());
      }
      if (!other.editLogs_.isEmpty()) {
        if (editLogs_.isEmpty()) {
          editLogs_ = other.editLogs_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEditLogsIsMutable();
          editLogs_.addAll(other.editLogs_);
        }
        onChanged();
      }
      if (other.getFetchSize() != 0) {
        setFetchSize(other.getFetchSize());
      }
      if (other.getHasMore() != false) {
        setHasMore(other.getHasMore());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>optional int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>optional int32 status = 1;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long beginTxid_ ;
    /**
     * <code>optional int64 beginTxid = 2;</code>
     */
    public long getBeginTxid() {
      return beginTxid_;
    }
    /**
     * <code>optional int64 beginTxid = 2;</code>
     */
    public Builder setBeginTxid(long value) {
      
      beginTxid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 beginTxid = 2;</code>
     */
    public Builder clearBeginTxid() {
      
      beginTxid_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList editLogs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEditLogsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        editLogs_ = new com.google.protobuf.LazyStringArrayList(editLogs_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEditLogsList() {
      return editLogs_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public int getEditLogsCount() {
      return editLogs_.size();
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public java.lang.String getEditLogs(int index) {
      return editLogs_.get(index);
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEditLogsBytes(int index) {
      return editLogs_.getByteString(index);
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public Builder setEditLogs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEditLogsIsMutable();
      editLogs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public Builder addEditLogs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEditLogsIsMutable();
      editLogs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public Builder addAllEditLogs(
        java.lang.Iterable<java.lang.String> values) {
      ensureEditLogsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, editLogs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public Builder clearEditLogs() {
      editLogs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 存放editlogs的
     * </pre>
     *
     * <code>repeated string editLogs = 3;</code>
     */
    public Builder addEditLogsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEditLogsIsMutable();
      editLogs_.add(value);
      onChanged();
      return this;
    }

    private int fetchSize_ ;
    /**
     * <pre>
     * 获取editlog的数量
     * </pre>
     *
     * <code>optional int32 fetchSize = 4;</code>
     */
    public int getFetchSize() {
      return fetchSize_;
    }
    /**
     * <pre>
     * 获取editlog的数量
     * </pre>
     *
     * <code>optional int32 fetchSize = 4;</code>
     */
    public Builder setFetchSize(int value) {
      
      fetchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 获取editlog的数量
     * </pre>
     *
     * <code>optional int32 fetchSize = 4;</code>
     */
    public Builder clearFetchSize() {
      
      fetchSize_ = 0;
      onChanged();
      return this;
    }

    private boolean hasMore_ ;
    /**
     * <pre>
     * 是否还有后续editlog
     * </pre>
     *
     * <code>optional bool hasMore = 5;</code>
     */
    public boolean getHasMore() {
      return hasMore_;
    }
    /**
     * <pre>
     * 是否还有后续editlog
     * </pre>
     *
     * <code>optional bool hasMore = 5;</code>
     */
    public Builder setHasMore(boolean value) {
      
      hasMore_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否还有后续editlog
     * </pre>
     *
     * <code>optional bool hasMore = 5;</code>
     */
    public Builder clearHasMore() {
      
      hasMore_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * 异常时提示消息
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 异常时提示消息
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 异常时提示消息
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 异常时提示消息
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 异常时提示消息
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iclouding.mfs.rpc.namenode.FetchEditLogResponse)
  }

  // @@protoc_insertion_point(class_scope:com.iclouding.mfs.rpc.namenode.FetchEditLogResponse)
  private static final com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse();
  }

  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchEditLogResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchEditLogResponse>() {
    public FetchEditLogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchEditLogResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchEditLogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchEditLogResponse> getParserForType() {
    return PARSER;
  }

  public com.iclouding.mfs.rpc.namenode.model.FetchEditLogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

