// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StandByNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

/**
 * Protobuf type {@code com.iclouding.mfs.rpc.namenode.FetchEditLogRequest}
 */
public  final class FetchEditLogRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iclouding.mfs.rpc.namenode.FetchEditLogRequest)
    FetchEditLogRequestOrBuilder {
  // Use FetchEditLogRequest.newBuilder() to construct.
  private FetchEditLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchEditLogRequest() {
    beginTxid_ = 0L;
    fetchSize_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchEditLogRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            beginTxid_ = input.readInt64();
            break;
          }
          case 16: {

            fetchSize_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.class, com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.Builder.class);
  }

  public static final int BEGINTXID_FIELD_NUMBER = 1;
  private long beginTxid_;
  /**
   * <code>optional int64 beginTxid = 1;</code>
   */
  public long getBeginTxid() {
    return beginTxid_;
  }

  public static final int FETCHSIZE_FIELD_NUMBER = 2;
  private int fetchSize_;
  /**
   * <code>optional int32 fetchSize = 2;</code>
   */
  public int getFetchSize() {
    return fetchSize_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (beginTxid_ != 0L) {
      output.writeInt64(1, beginTxid_);
    }
    if (fetchSize_ != 0) {
      output.writeInt32(2, fetchSize_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (beginTxid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, beginTxid_);
    }
    if (fetchSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, fetchSize_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest)) {
      return super.equals(obj);
    }
    com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest other = (com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest) obj;

    boolean result = true;
    result = result && (getBeginTxid()
        == other.getBeginTxid());
    result = result && (getFetchSize()
        == other.getFetchSize());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + BEGINTXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBeginTxid());
    hash = (37 * hash) + FETCHSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFetchSize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iclouding.mfs.rpc.namenode.FetchEditLogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iclouding.mfs.rpc.namenode.FetchEditLogRequest)
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.class, com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.Builder.class);
    }

    // Construct using com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      beginTxid_ = 0L;

      fetchSize_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iclouding.mfs.rpc.namenode.model.StandbyNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor;
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest getDefaultInstanceForType() {
      return com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.getDefaultInstance();
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest build() {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest buildPartial() {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest result = new com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest(this);
      result.beginTxid_ = beginTxid_;
      result.fetchSize_ = fetchSize_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest) {
        return mergeFrom((com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest other) {
      if (other == com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest.getDefaultInstance()) return this;
      if (other.getBeginTxid() != 0L) {
        setBeginTxid(other.getBeginTxid());
      }
      if (other.getFetchSize() != 0) {
        setFetchSize(other.getFetchSize());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long beginTxid_ ;
    /**
     * <code>optional int64 beginTxid = 1;</code>
     */
    public long getBeginTxid() {
      return beginTxid_;
    }
    /**
     * <code>optional int64 beginTxid = 1;</code>
     */
    public Builder setBeginTxid(long value) {
      
      beginTxid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 beginTxid = 1;</code>
     */
    public Builder clearBeginTxid() {
      
      beginTxid_ = 0L;
      onChanged();
      return this;
    }

    private int fetchSize_ ;
    /**
     * <code>optional int32 fetchSize = 2;</code>
     */
    public int getFetchSize() {
      return fetchSize_;
    }
    /**
     * <code>optional int32 fetchSize = 2;</code>
     */
    public Builder setFetchSize(int value) {
      
      fetchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 fetchSize = 2;</code>
     */
    public Builder clearFetchSize() {
      
      fetchSize_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iclouding.mfs.rpc.namenode.FetchEditLogRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iclouding.mfs.rpc.namenode.FetchEditLogRequest)
  private static final com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest();
  }

  public static com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchEditLogRequest>
      PARSER = new com.google.protobuf.AbstractParser<FetchEditLogRequest>() {
    public FetchEditLogRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchEditLogRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchEditLogRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchEditLogRequest> getParserForType() {
    return PARSER;
  }

  public com.iclouding.mfs.rpc.namenode.model.FetchEditLogRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

