// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StandByNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface FetchEditLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.FetchEditLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 beginTxid = 1;</code>
   */
  long getBeginTxid();

  /**
   * <code>optional int32 fetchSize = 2;</code>
   */
  int getFetchSize();
}
