// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.iclouding.mfs.rpc.namenode.model;

/**
 * Protobuf type {@code com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest}
 */
public  final class InformReplicaReceivedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest)
    InformReplicaReceivedRequestOrBuilder {
  // Use InformReplicaReceivedRequest.newBuilder() to construct.
  private InformReplicaReceivedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InformReplicaReceivedRequest() {
    filePath_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private InformReplicaReceivedRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            filePath_ = s;
            break;
          }
          case 18: {
            com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder subBuilder = null;
            if (dataNodeInfo_ != null) {
              subBuilder = dataNodeInfo_.toBuilder();
            }
            dataNodeInfo_ = input.readMessage(com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataNodeInfo_);
              dataNodeInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.class, com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.Builder.class);
  }

  public static final int FILE_PATH_FIELD_NUMBER = 1;
  private volatile java.lang.Object filePath_;
  /**
   * <code>optional string file_path = 1;</code>
   */
  public java.lang.String getFilePath() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePath_ = s;
      return s;
    }
  }
  /**
   * <code>optional string file_path = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATANODEINFO_FIELD_NUMBER = 2;
  private com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto dataNodeInfo_;
  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
   */
  public boolean hasDataNodeInfo() {
    return dataNodeInfo_ != null;
  }
  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
   */
  public com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto getDataNodeInfo() {
    return dataNodeInfo_ == null ? com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.getDefaultInstance() : dataNodeInfo_;
  }
  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
   */
  public com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder getDataNodeInfoOrBuilder() {
    return getDataNodeInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filePath_);
    }
    if (dataNodeInfo_ != null) {
      output.writeMessage(2, getDataNodeInfo());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filePath_);
    }
    if (dataNodeInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDataNodeInfo());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest)) {
      return super.equals(obj);
    }
    com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest other = (com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest) obj;

    boolean result = true;
    result = result && getFilePath()
        .equals(other.getFilePath());
    result = result && (hasDataNodeInfo() == other.hasDataNodeInfo());
    if (hasDataNodeInfo()) {
      result = result && getDataNodeInfo()
          .equals(other.getDataNodeInfo());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFilePath().hashCode();
    if (hasDataNodeInfo()) {
      hash = (37 * hash) + DATANODEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDataNodeInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest)
      com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.class, com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.Builder.class);
    }

    // Construct using com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      filePath_ = "";

      if (dataNodeInfoBuilder_ == null) {
        dataNodeInfo_ = null;
      } else {
        dataNodeInfo_ = null;
        dataNodeInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor;
    }

    public com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest getDefaultInstanceForType() {
      return com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.getDefaultInstance();
    }

    public com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest build() {
      com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest buildPartial() {
      com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest result = new com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest(this);
      result.filePath_ = filePath_;
      if (dataNodeInfoBuilder_ == null) {
        result.dataNodeInfo_ = dataNodeInfo_;
      } else {
        result.dataNodeInfo_ = dataNodeInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest) {
        return mergeFrom((com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest other) {
      if (other == com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest.getDefaultInstance()) return this;
      if (!other.getFilePath().isEmpty()) {
        filePath_ = other.filePath_;
        onChanged();
      }
      if (other.hasDataNodeInfo()) {
        mergeDataNodeInfo(other.getDataNodeInfo());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object filePath_ = "";
    /**
     * <code>optional string file_path = 1;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string file_path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string file_path = 1;</code>
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 1;</code>
     */
    public Builder clearFilePath() {
      
      filePath_ = getDefaultInstance().getFilePath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 1;</code>
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filePath_ = value;
      onChanged();
      return this;
    }

    private com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto dataNodeInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder> dataNodeInfoBuilder_;
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public boolean hasDataNodeInfo() {
      return dataNodeInfoBuilder_ != null || dataNodeInfo_ != null;
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto getDataNodeInfo() {
      if (dataNodeInfoBuilder_ == null) {
        return dataNodeInfo_ == null ? com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.getDefaultInstance() : dataNodeInfo_;
      } else {
        return dataNodeInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public Builder setDataNodeInfo(com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto value) {
      if (dataNodeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataNodeInfo_ = value;
        onChanged();
      } else {
        dataNodeInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public Builder setDataNodeInfo(
        com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder builderForValue) {
      if (dataNodeInfoBuilder_ == null) {
        dataNodeInfo_ = builderForValue.build();
        onChanged();
      } else {
        dataNodeInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public Builder mergeDataNodeInfo(com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto value) {
      if (dataNodeInfoBuilder_ == null) {
        if (dataNodeInfo_ != null) {
          dataNodeInfo_ =
            com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.newBuilder(dataNodeInfo_).mergeFrom(value).buildPartial();
        } else {
          dataNodeInfo_ = value;
        }
        onChanged();
      } else {
        dataNodeInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public Builder clearDataNodeInfo() {
      if (dataNodeInfoBuilder_ == null) {
        dataNodeInfo_ = null;
        onChanged();
      } else {
        dataNodeInfo_ = null;
        dataNodeInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder getDataNodeInfoBuilder() {
      
      onChanged();
      return getDataNodeInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    public com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder getDataNodeInfoOrBuilder() {
      if (dataNodeInfoBuilder_ != null) {
        return dataNodeInfoBuilder_.getMessageOrBuilder();
      } else {
        return dataNodeInfo_ == null ?
            com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.getDefaultInstance() : dataNodeInfo_;
      }
    }
    /**
     * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder> 
        getDataNodeInfoFieldBuilder() {
      if (dataNodeInfoBuilder_ == null) {
        dataNodeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto.Builder, com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder>(
                getDataNodeInfo(),
                getParentForChildren(),
                isClean());
        dataNodeInfo_ = null;
      }
      return dataNodeInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iclouding.mfs.rpc.namenode.InformReplicaReceivedRequest)
  private static final com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest();
  }

  public static com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InformReplicaReceivedRequest>
      PARSER = new com.google.protobuf.AbstractParser<InformReplicaReceivedRequest>() {
    public InformReplicaReceivedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InformReplicaReceivedRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InformReplicaReceivedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InformReplicaReceivedRequest> getParserForType() {
    return PARSER;
  }

  public com.iclouding.mfs.rpc.namenode.model.InformReplicaReceivedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

