// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mfs.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class MFSProtols {
  private MFSProtols() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_DataNodeInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_DataNodeInfoProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmfs.proto\022\036com.iclouding.mfs.rpc.namen" +
      "ode\"p\n\021DataNodeInfoProto\022\n\n\002ip\030\001 \001(\t\022\020\n\010" +
      "hostname\030\002 \001(\t\022\020\n\010dataPort\030\003 \001(\005\022\025\n\rtota" +
      "lDiskSize\030\004 \001(\003\022\024\n\014usedDiskSize\030\005 \001(\003B4\n" +
      "$com.iclouding.mfs.rpc.namenode.modelB\nM" +
      "FSProtolsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_DataNodeInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_DataNodeInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_DataNodeInfoProto_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "DataPort", "TotalDiskSize", "UsedDiskSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
