// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\036com.iclouding." +
      "mfs.rpc.namenode\032\tmfs.proto\"Z\n\017RegisterR" +
      "equest\022G\n\014dataNodeInfo\030\001 \001(\01321.com.iclou" +
      "ding.mfs.rpc.namenode.DataNodeInfoProto\"" +
      "\"\n\020RegisterResponse\022\016\n\006status\030\001 \001(\005\"0\n\020H" +
      "eartbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030" +
      "\002 \001(\t\"#\n\021HeartbeatResponse\022\016\n\006status\030\001 \001" +
      "(\005\"z\n\034InformReplicaReceivedRequest\022\021\n\tfi" +
      "le_path\030\001 \001(\t\022G\n\014dataNodeInfo\030\002 \001(\01321.co" +
      "m.iclouding.mfs.rpc.namenode.DataNodeInf",
      "oProto\"/\n\035InformReplicaReceivedResponse\022" +
      "\016\n\006status\030\001 \001(\005B=\n$com.iclouding.mfs.rpc" +
      ".namenode.modelB\020NameNodeRpcModelP\001\240\001\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iclouding.mfs.rpc.namenode.model.MFSProtols.getDescriptor(),
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_RegisterRequest_descriptor,
        new java.lang.String[] { "DataNodeInfo", });
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iclouding_mfs_rpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedRequest_descriptor,
        new java.lang.String[] { "FilePath", "DataNodeInfo", });
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_InformReplicaReceivedResponse_descriptor,
        new java.lang.String[] { "Status", });
    com.iclouding.mfs.rpc.namenode.model.MFSProtols.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
