// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 1;</code>
   */
  boolean hasDataNodeInfo();
  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 1;</code>
   */
  com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProto getDataNodeInfo();
  /**
   * <code>optional .com.iclouding.mfs.rpc.namenode.DataNodeInfoProto dataNodeInfo = 1;</code>
   */
  com.iclouding.mfs.rpc.namenode.model.DataNodeInfoProtoOrBuilder getDataNodeInfoOrBuilder();
}
