// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface RenameDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.RenameDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string srcDir = 1;</code>
   */
  java.lang.String getSrcDir();
  /**
   * <code>optional string srcDir = 1;</code>
   */
  com.google.protobuf.ByteString
      getSrcDirBytes();

  /**
   * <code>optional string destDir = 2;</code>
   */
  java.lang.String getDestDir();
  /**
   * <code>optional string destDir = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestDirBytes();
}
