// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

/**
 * Protobuf type {@code com.iclouding.mfs.rpc.namenode.RenameDirRequest}
 */
public  final class RenameDirRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iclouding.mfs.rpc.namenode.RenameDirRequest)
    RenameDirRequestOrBuilder {
  // Use RenameDirRequest.newBuilder() to construct.
  private RenameDirRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenameDirRequest() {
    srcDir_ = "";
    destDir_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RenameDirRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            srcDir_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            destDir_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.class, com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.Builder.class);
  }

  public static final int SRCDIR_FIELD_NUMBER = 1;
  private volatile java.lang.Object srcDir_;
  /**
   * <code>optional string srcDir = 1;</code>
   */
  public java.lang.String getSrcDir() {
    java.lang.Object ref = srcDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcDir_ = s;
      return s;
    }
  }
  /**
   * <code>optional string srcDir = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSrcDirBytes() {
    java.lang.Object ref = srcDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTDIR_FIELD_NUMBER = 2;
  private volatile java.lang.Object destDir_;
  /**
   * <code>optional string destDir = 2;</code>
   */
  public java.lang.String getDestDir() {
    java.lang.Object ref = destDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destDir_ = s;
      return s;
    }
  }
  /**
   * <code>optional string destDir = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDestDirBytes() {
    java.lang.Object ref = destDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSrcDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcDir_);
    }
    if (!getDestDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destDir_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSrcDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcDir_);
    }
    if (!getDestDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destDir_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iclouding.mfs.rpc.namenode.model.RenameDirRequest)) {
      return super.equals(obj);
    }
    com.iclouding.mfs.rpc.namenode.model.RenameDirRequest other = (com.iclouding.mfs.rpc.namenode.model.RenameDirRequest) obj;

    boolean result = true;
    result = result && getSrcDir()
        .equals(other.getSrcDir());
    result = result && getDestDir()
        .equals(other.getDestDir());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SRCDIR_FIELD_NUMBER;
    hash = (53 * hash) + getSrcDir().hashCode();
    hash = (37 * hash) + DESTDIR_FIELD_NUMBER;
    hash = (53 * hash) + getDestDir().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iclouding.mfs.rpc.namenode.model.RenameDirRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iclouding.mfs.rpc.namenode.RenameDirRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iclouding.mfs.rpc.namenode.RenameDirRequest)
      com.iclouding.mfs.rpc.namenode.model.RenameDirRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.class, com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.Builder.class);
    }

    // Construct using com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      srcDir_ = "";

      destDir_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.internal_static_com_iclouding_mfs_rpc_namenode_RenameDirRequest_descriptor;
    }

    public com.iclouding.mfs.rpc.namenode.model.RenameDirRequest getDefaultInstanceForType() {
      return com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.getDefaultInstance();
    }

    public com.iclouding.mfs.rpc.namenode.model.RenameDirRequest build() {
      com.iclouding.mfs.rpc.namenode.model.RenameDirRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iclouding.mfs.rpc.namenode.model.RenameDirRequest buildPartial() {
      com.iclouding.mfs.rpc.namenode.model.RenameDirRequest result = new com.iclouding.mfs.rpc.namenode.model.RenameDirRequest(this);
      result.srcDir_ = srcDir_;
      result.destDir_ = destDir_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iclouding.mfs.rpc.namenode.model.RenameDirRequest) {
        return mergeFrom((com.iclouding.mfs.rpc.namenode.model.RenameDirRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iclouding.mfs.rpc.namenode.model.RenameDirRequest other) {
      if (other == com.iclouding.mfs.rpc.namenode.model.RenameDirRequest.getDefaultInstance()) return this;
      if (!other.getSrcDir().isEmpty()) {
        srcDir_ = other.srcDir_;
        onChanged();
      }
      if (!other.getDestDir().isEmpty()) {
        destDir_ = other.destDir_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iclouding.mfs.rpc.namenode.model.RenameDirRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iclouding.mfs.rpc.namenode.model.RenameDirRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object srcDir_ = "";
    /**
     * <code>optional string srcDir = 1;</code>
     */
    public java.lang.String getSrcDir() {
      java.lang.Object ref = srcDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string srcDir = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrcDirBytes() {
      java.lang.Object ref = srcDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string srcDir = 1;</code>
     */
    public Builder setSrcDir(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string srcDir = 1;</code>
     */
    public Builder clearSrcDir() {
      
      srcDir_ = getDefaultInstance().getSrcDir();
      onChanged();
      return this;
    }
    /**
     * <code>optional string srcDir = 1;</code>
     */
    public Builder setSrcDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcDir_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destDir_ = "";
    /**
     * <code>optional string destDir = 2;</code>
     */
    public java.lang.String getDestDir() {
      java.lang.Object ref = destDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string destDir = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestDirBytes() {
      java.lang.Object ref = destDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string destDir = 2;</code>
     */
    public Builder setDestDir(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string destDir = 2;</code>
     */
    public Builder clearDestDir() {
      
      destDir_ = getDefaultInstance().getDestDir();
      onChanged();
      return this;
    }
    /**
     * <code>optional string destDir = 2;</code>
     */
    public Builder setDestDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destDir_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iclouding.mfs.rpc.namenode.RenameDirRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iclouding.mfs.rpc.namenode.RenameDirRequest)
  private static final com.iclouding.mfs.rpc.namenode.model.RenameDirRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iclouding.mfs.rpc.namenode.model.RenameDirRequest();
  }

  public static com.iclouding.mfs.rpc.namenode.model.RenameDirRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenameDirRequest>
      PARSER = new com.google.protobuf.AbstractParser<RenameDirRequest>() {
    public RenameDirRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RenameDirRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RenameDirRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenameDirRequest> getParserForType() {
    return PARSER;
  }

  public com.iclouding.mfs.rpc.namenode.model.RenameDirRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

