// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface RenameDirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.RenameDirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 路径
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   * 路径
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>optional int32 status = 2;</code>
   */
  int getStatus();

  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 异常时提示消息
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
