// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StandByNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class StandbyNameNodeProtol {
  private StandbyNameNodeProtol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033StandByNameNodeProtol.proto\022\036com.iclou" +
      "ding.mfs.rpc.namenode\";\n\023FetchEditLogReq" +
      "uest\022\021\n\tbeginTxid\030\001 \001(\003\022\021\n\tfetchSize\030\002 \001" +
      "(\005\"\200\001\n\024FetchEditLogResponse\022\016\n\006status\030\001 " +
      "\001(\005\022\021\n\tbeginTxid\030\002 \001(\003\022\020\n\010editLogs\030\003 \003(\t" +
      "\022\021\n\tfetchSize\030\004 \001(\005\022\017\n\007hasMore\030\005 \001(\010\022\017\n\007" +
      "message\030\006 \001(\tB?\n$com.iclouding.mfs.rpc.n" +
      "amenode.modelB\025StandbyNameNodeProtolP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor,
        new java.lang.String[] { "BeginTxid", "FetchSize", });
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor,
        new java.lang.String[] { "Status", "BeginTxid", "EditLogs", "FetchSize", "HasMore", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
