// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StandByNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public final class StandbyNameNodeProtol {
  private StandbyNameNodeProtol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033StandByNameNodeProtol.proto\022\036com.iclou" +
      "ding.mfs.rpc.namenode\"=\n\023FetchEditLogReq" +
      "uest\022\022\n\nbegin_txid\030\001 \001(\003\022\022\n\nfetch_size\030\002" +
      " \001(\005\"\204\001\n\024FetchEditLogResponse\022\016\n\006status\030" +
      "\001 \001(\005\022\022\n\nbegin_txid\030\002 \001(\003\022\021\n\tedit_logs\030\003" +
      " \003(\t\022\022\n\nfetch_size\030\004 \001(\005\022\020\n\010has_more\030\005 \001" +
      "(\010\022\017\n\007message\030\006 \001(\tBB\n$com.iclouding.mfs" +
      ".rpc.namenode.modelB\025StandbyNameNodeProt" +
      "olP\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogRequest_descriptor,
        new java.lang.String[] { "BeginTxid", "FetchSize", });
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iclouding_mfs_rpc_namenode_FetchEditLogResponse_descriptor,
        new java.lang.String[] { "Status", "BeginTxid", "EditLogs", "FetchSize", "HasMore", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
