// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeProtol.proto

package com.iclouding.mfs.rpc.namenode.model;

public interface UploadFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iclouding.mfs.rpc.namenode.UploadFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string md5 = 2;</code>
   */
  java.lang.String getMd5();
  /**
   * <code>optional string md5 = 2;</code>
   */
  com.google.protobuf.ByteString
      getMd5Bytes();

  /**
   * <code>optional bytes content = 3;</code>
   */
  com.google.protobuf.ByteString getContent();
}
