// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.iclouding.mimi.namenode.rpc.service;

public final class NameNodeRpcServer {
  private NameNodeRpcServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\037com.iclouding" +
      ".mimi.namenode.rpc\032\026NameNodeRpcModel.pro" +
      "to2\366\001\n\017NameNodeService\022o\n\010register\0220.com" +
      ".iclouding.mimi.namenode.rpc.RegisterReq" +
      "uest\0321.com.iclouding.mimi.namenode.rpc.R" +
      "egisterResponse\022r\n\theartbeat\0221.com.iclou" +
      "ding.mimi.namenode.rpc.HeartbeatRequest\032" +
      "2.com.iclouding.mimi.namenode.rpc.Heartb" +
      "eatResponseB>\n\'com.iclouding.mimi.nameno" +
      "de.rpc.serviceB\021NameNodeRpcServerP\001b\006pro",
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iclouding.mimi.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.iclouding.mimi.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
