// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientNameNodeServer.proto

package com.iclouding.mfs.rpc.namenode.service;

public final class ClientNameNodeServer {
  private ClientNameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ClientNameNodeServer.proto\022\036com.icloud" +
      "ing.mfs.rpc.namenode\032\032ClientNameNodeProt" +
      "ol.proto2\366\003\n\025ClientNameNodeService\022d\n\005mk" +
      "dir\022,.com.iclouding.mfs.rpc.namenode.MkD" +
      "irRequest\032-.com.iclouding.mfs.rpc.nameno" +
      "de.MkDirResponse\022s\n\ncreateFile\0221.com.icl" +
      "ouding.mfs.rpc.namenode.CreateFileReques" +
      "t\0322.com.iclouding.mfs.rpc.namenode.Creat" +
      "eFileResponse\022q\n\nrenamedirs\0220.com.icloud" +
      "ing.mfs.rpc.namenode.RenameDirRequest\0321.",
      "com.iclouding.mfs.rpc.namenode.RenameDir" +
      "Response\022\216\001\n\023allocationDataNodes\022:.com.i" +
      "clouding.mfs.rpc.namenode.AllocationData" +
      "NodesRequest\032;.com.iclouding.mfs.rpc.nam" +
      "enode.AllocationDataNodesResponseBC\n&com" +
      ".iclouding.mfs.rpc.namenode.serviceB\024Cli" +
      "entNameNodeServerP\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.getDescriptor(),
        }, assigner);
    com.iclouding.mfs.rpc.namenode.model.ClientNameNodeProtol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
