// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.iclouding.mfs.rpc.namenode.service;

public final class NameNodeRpcServer {
  private NameNodeRpcServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\036com.iclouding" +
      ".mfs.rpc.namenode\032\026NameNodeRpcModel.prot" +
      "o2\362\001\n\017NameNodeService\022m\n\010register\022/.com." +
      "iclouding.mfs.rpc.namenode.RegisterReque" +
      "st\0320.com.iclouding.mfs.rpc.namenode.Regi" +
      "sterResponse\022p\n\theartbeat\0220.com.icloudin" +
      "g.mfs.rpc.namenode.HeartbeatRequest\0321.co" +
      "m.iclouding.mfs.rpc.namenode.HeartbeatRe" +
      "sponseB@\n&com.iclouding.mfs.rpc.namenode" +
      ".serviceB\021NameNodeRpcServerP\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.iclouding.mfs.rpc.namenode.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
